export const aggregateData = {
  categories: [
    'bloom-filter',
    'cryptography',
    'disjoint-set',
    'doubly-linked-list',
    'graph',
    'hash-table',
    'heap',
    'linked-list',
    'math',
    'ml',
    'priority-queue',
    'queue',
    'search',
    'sets',
    'sorting',
    'stack',
    'string',
    'tree',
    'trie',
    'other',
  ],
};
